[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F446ZE"
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tlink-rp.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "linker=flip-link",
    "-C", "llvm-args=--inline-threshold=5",
    "-C", "no-vectorize-loops",
]

[env]
DEFMT_LOG = "info"
