[package]
name = "blinds_controller"
version = "0.1.0"
edition = "2021"

[features]
default = ["btt_skr_pico_v1_0"]
driver_tmc2209 = ["tmc2209", "configurable_driver"]
btt_skr_pico_v1_0 = ["driver_tmc2209"]
configurable_driver = []

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"

defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

embassy-executor = { version = "0.6", features = ["arch-cortex-m", "executor-thread", "defmt", "integrated-timers"] }
embassy-time = { version = "0.3", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { version = "0.2", features = ["defmt", "time-driver", "critical-section-impl"] }

embedded-hal = "0.2"
blinds_sequencer = { git = "https://github.com/thinkier/blinds_sequencer" }
tmc2209 = { version = "^0.2", optional = true }

static_cell = "2"
portable-atomic = { version = "1.10", features = ["critical-section"] }
heapless = "0.8"

[profile.release]
lto = true
opt-level = "s"
incremental = false
codegen-units = 1
# note: debug = true is okay - debuginfo isn't flashed to the device!
debug = true

[profile.dev]
lto = true
