[package]
name = "btt_octopus"
version = "0.1.0"
edition = "2021"

[dependencies]


[profile.release]
lto = true
opt-level = "s"
incremental = false
codegen-units = 1
# note: debug = true is okay - debuginfo isn't flashed to the device!
debug = true

[profile.dev]
lto = true
